github.rest.client.base-url: https://api.github.com
  
# Custom path for the API docs (JSON/YAML)
springdoc.api-docs.path: /api-docs

# Custom path for the Swagger UI
springdoc.swagger-ui.path: /swagger-ui.html